### ISSUE TITLE
Which version of Oculus Runtime for Windows?

### ISSUE THREAD

**Issue by jpmckinney** [BeAnotherLab/The-Machine-to-be-Another#5]
The readme links to 0.4.4, but the latest version is 0.8.0.0.

**Comment by marteroel** [comment]
Yeah, we have tested with 0.4.4 and kept that version as our current. You can try with a more recent version and let us know how it works. Though this example doesn't run on Mac, 0.4.4 is also the last Oculus Runtime version that runs on Mac.

**Comment by ReallyRad** [comment]
0.4.4 is the latest tested, I think from 0.7.0 extended mode is not allowed anymore. It you are interested in contributing, look at our TODOs

**Comment by jpmckinney** [comment]
Thanks!

**Comment by rempsyc** [comment]
I tried installing Oculus Runtime 0.4.4 on a new (clean install) Windows 10 laptop and the computer wouldn't get past the booting screen... I restored the computer then tried 0.7.0 as apparently, Windows only supports 0.7.0 and later versions of the runtime, and the booting problem seems to be a common one: https://www.reddit.com/r/oculus/comments/4auv7l/help_installing_oculus_runtime_prevents_computer/

With 0.7.0 I could see my screen in the Oculus but the Config Utility doesn't support extended mode, and The-Machine-to-be-Another.exe would crash at startup. I think it's because the Config Utility wouldn't detect the Oculus ("HMD powered off check HDMI connection"). In the end, I tried runtime 0.5.1, and with this version, the problematic driver (riftenabler.sys file) doesn't automatically installs and the runtime still detects the Oculus. AND The-Machine-to-be-Another.exe still works!! Thought it was worth sharing this troubleshooting. I found this thread useful to solve the issue: https://www.reddit.com/r/oculus/comments/3ssl19/windows_10_gaming_laptop_doesnt_see_dk2/
