### ISSUE TITLE
Compiling on OS X

### ISSUE THREAD

**Issue by jpmckinney** [BeAnotherLab/The-Machine-to-be-Another#6]
I'm on OS X 10.11 (El Capitan), and I'm seeing:

```
of_v0.8.4_osx_release/apps/myApps/The-Machine-to-be-Another/src/main.cpp:3:10: 'ofxXmlSettings.h' file not found
```

Let me know what additional information would be useful.

**Comment by ReallyRad** [comment]
We haven't compiled on Mac OS X since very early versions, which why the xcode project is not up to date. ofxXmlSettings is a default openframeworks addon but probably wasn't added to the project. 
The whole project needs an update to of 0.9 to have a chance to compile on OS X. We are using modified versions of outdated addons (ofxFenster and ofxUI) that I can't help you compile for OS X.

**Comment by jpmckinney** [comment]
Thanks for explaining!
